import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import CartProvider from '@/context/CartContext'

const expo2 = localFont({ src: '../fonts/Exo2-VariableFont_wght.ttf' })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${expo2.className} antialiased`}>
				<CartProvider>
					<Header />
					{children}
					<Footer />
				</CartProvider>
			</body>
		</html>
	)
}
